# Generated by Django 3.2.10 on 2021-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_contity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
