# Generated by Django 3.2.10 on 2021-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_stock_contity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_contity',
            field=models.PositiveIntegerField(),
        ),
    ]
